Butterfly/Butterfly/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('Butterfly_Home.urls')),
    path('plants/', include('Butterfly_Plants.urls')),
    path('seeds/', include('Butterfly_Seeds.urls',)),
    path('garden/', include('garden.urls',)),

    # path('accounts/', include('socialdjango.urls',))
]
# + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

Butterfly/Butterfly_About/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.about1, name='about1')
]

Butterfly/Butterfly_Home/urls.py
from . import views
from django.urls import path

app_name = 'home'

urlpatterns = [
    path ('', views.index, name='index'),
]

Butterfly/Butterfly_Plants/urls.py
from . import views
from django.urls import path

app_name = 'plants'

urlpatterns = [
    path('', views.plants, name= 'plants'),
]

Butterfly/Butterfly_Seeds/urls.py
from . import views
from django.urls import path

app_name = 'seeds'

urlpatterns = [
    path('', views.seeds, name= 'seeds'),
]

Butterfly/Cart/urls.py
from . import views
from django.urls import path

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name= 'cart'),
]

Butterfly/garden/urls.py
from . import views
from django.urls import path

app_name = 'garden'

urlpatterns = [
    path('', views.garden, name= 'garden'),
]

Butterfly/garden/models.py
from django.db import models

# Create your models here.

Butterfly/Butterfly_About/views.py
from django.shortcuts import render
from django.http import HttpResponse

Butterfly/Butterfly_Home/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return render(request, 'Butterfly_Home/index.html')

Butterfly/Butterfly_Plants/views.py
from django.shortcuts import render
from django.http import HttpResponse

def plants(request):
    return render(request, "Butterfly_Plants/plants.html")

# Create your views here.

Butterfly/Butterfly_Seeds/views.py
from django.shortcuts import render
from django.http import HttpResponse

def seeds(request):
    return render(request, "Seed/seeds.html")

# Create your views here.

Butterfly/Cart/views.py
from django.shortcuts import render
from django.http import HttpResponse

def cart(request):
    return render(request, "cart/cart.html")

Butterfly/garden/views.py
from django.shortcuts import render
from django.http import HttpResponse

def garden(request):
    return render(request, "garden/garden.html")

# Create your views here.

Butterfly/socialdjango/views.py
from django.shortcuts import render

# Create your views here.

Butterfly/templates/Butterfly/footer.html
<footer>

         <div id="footer">

            <div class="footer_sub" style="left: 50px">
                <h2>Our Story</h2>
                <p>E-commerce website. you can buy any plant of your choice, we will  deliver your plant to your house.E-commerce website. you can buy any plant of your choice, we will  deliver your plant to your house.E-commerce website. you can buy any plant of your choice, we will  deliver your plant to your house.E-commerce website. you can buy any plant of your choice, we will  deliver your plant to your house.E-commerce website. you can buy any plant of your choice, we will  deliver your plant to your house.E-commerce website. you can buy any plant of your choice, we will  deliver your plant to your house..E-commerce website. you can buy any plant of your choice, we will  deliver your plant to your house..E-commerce website. you can buy any plant of your choice, we will  deliver your plant to your house..E-commerce website. you can buy any plant of your choice, we will  deliver your plant to your house <span><a href="#">Read more..</a></span></p>

                <div class="footer_sub_2" style="Left:50px">



                  <center>
                    <h2>Categories</h2>
                    <ul>
                      <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
                      <li><a href="#"><i class="fa fa-info-circle" aria-hidden="true"></i> About Us</a></li>
                      <li><a href="#"><i class="fa fa-gift"></i> Offers </a></li>
                      <li><a href="#"><i class="fa fa-image"></i> Gallery </a></li>
                      <li><a href="#"><i class="fa fa-headphones"></i> Customer Services </a></li>
                    </ul>
                  </center>
                </div>

                <div class="footer_sub_3">
                  <center>
                    <h2>Social links</h2>
                    <ul>
                      <li><a href="#"><i class="fa fa-Facebook"></i> Facebook</a></li>
                      <li><a href="#"><i class="fa fa-instagram"></i> Instagram</a></li>
                      <li><a href="#"><i class="fa fa-google-plus"></i> Google+</a></li>
                      <li><a href="#"><i class="fa fa-Youtube"></i> Youtube</a></li>
                      <li><a href="#"><i class="fa fa-Twitter"></i> Twitter</a></li>
                      <li><a href="#"><i class="fa fa-Linkedin"></i> Linkedin</a></li>
                    </ul>
                  </center>
                </div>
                <div class="footer_sub_4">
                  <center>
                    <h2>Subscribe Us</h2>
                    <input type="text" name="subs" placeholder="Write your email" class="subs">
                    <input style="margin-left: 250px;" type="submit" name="submit_btn" value="Subscribe" class="sub_btn">
                    <p style="font-size: 13px;" class="sub_p">Enter your e-mail id to get notification by us</p>
                  </center>

                </div>

            </div>

          </div>

</footer>

Butterfly/templates/Butterfly/header.html
<header>
{% load static %}
<head>
    <title>::e plantation::</title>

    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


</head>



    <div id="wrapper">
      <div id="header">
        <div id="subheader">
          <div class="container" style="margin-top: 15px">
            <p>Buy any plant you want</p>
            <a href="#"> Guest </a><a href="#">Consumer</a><a href="#"> Help</a><a href="#"> Download App</a>
          </div>

        </div>
        <!--==main header==-->
        <div id="main-header"  style="margin-top: -5">
            <!--logo-->
            <div id="logo">
              <span id="ist">E-</span><span id="iist">Plantation.com</span>


            </div>
            <!--==search area==-->
            <div id="search">
              <form action="">
                <input class="search-area" type="text" name="text" placeholder="Search here">
                <input class="search-btn" type="submit" name="submit" value="SEARCH">

              </form>
            </div>
            <!--==user-menu==-->
            <div id="user-menu">
              <li><a href="#"><i class="fa fa-shopping-cart"></i> Cart </a></li>
              <li><a href="#"> <i class="fa fa-github-alt"></i> Account</a></li>


            </div>
        </div>
      </div>

        <!---====navigation bar====---->


      <nav style="background-color: #1aaa1a;" class="navbar navbar-expand-lg">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href= {% url "home:index" %} ><i class="fa fa-home"></i> Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="#"><i class="fa fa-info-circle" aria-hidden="true"></i> About </a>
            </li>
            <li class="nav-item dropdown active">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-gift"></i>
                Offers
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Offer1</a>
                <a class="dropdown-item" href="#"> Offer1 </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item dropdown active">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-image"></i>
                Gallery
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Our Gardens</a>
                <a class="dropdown-item" href="#">Our Nurseries</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="#"><i class="fa fa-headphones"></i> Customer Service </a>
            </li>

          </ul>
        </div>
      </nav>

</header>

Butterfly/templates/Butterfly_Home/index.html
{% load staticfiles %}
{% load static %}



{% include 'Butterfly/header.html' %}

<body>
  {% block content %}

                <!--=========home-slider==-->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>



  <div id="slider">

    <div style="margin-top: 120px; top: 5px" id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <img src="/static/Plants/Untitled-1.jpg" style="width:200%; height: 50%;">
      </div>

      <div class="item">
        <img src="/static/Plants/Untitled-2.jpg" style="width:200%; height: 50%;">
      </div>

      <div class="item">
        <img src="/static/Plants/Untitled-3.jpg" style="width:200%; height: 50%;">
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev" style="top: 35.5px;">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next" style="top: 35.5px;">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>


  </div>
</div>


            <!--======category circles===----->

            <div id="heading-block" style="margin-left: 50px">
                <h2>Category</h2>
            </div>
                <!---1st catbox------->
                <a href = {% url 'plants:plants' %} >
                  <div class="catbox" style="margin-left: 50px">
                    <img src="/static/Plants/lantssfinal.jpg" alt="Plants">

                    <span>Plants</span>

                  </div>
                </a>
                 <!---2nd catbox------->
                 <a href={% url 'seeds:seeds' %} >
                   <div class="catbox" style="margin-left: 50px">
                     <img src="/static/Plants/seedsfinal.jpg" alt="Plants">
                     <span>Seeds</span>

                   </div>
                 </a>

                 <!---3rd catbox------->

                 <a href= {% url 'garden:garden' %} >
                   <div class="catbox" style="margin-left: 50px">
                     <img src="/static/Plants/gardenFinal.jpg" alt="Plants">
                     <span>Garden Decoration</span>

                   </div>
                 </a>

        <!---========HEADING OF CATEGORY======---->

                <div id="heading-block">
                  <h2 style="margin-left: 50px">Some Of Our Special Plants</h2>
                </div>

                <div class="prod-container">

                    <!---1st product----->

                    <div class="prod-box" style="margin-left: 50px">
                      <img src="/static/Plants/flowerfinal.jpg" alt="Some of our best plants" >
                      <div class="prod-trans" >
                        <div class="prod-feature">

                            <p>Rose</p>
                            <p style="color:#fff;font-weight: bold">Price $7.7</p>
                            <input type="button" value="Add to cart">


                        </div>

                      </div>
                    </div>

                         <!---2nd product----->

                    <div class="prod-box" style="margin-left: 50px">
                      <img src="/static/Plants/flowerfinal2.jpg" alt="Some of our best plants" >
                      <div class="prod-trans" >
                        <div class="prod-feature">

                            <p>Sun Flower</p>
                            <p style="color:#fff;font-weight: bold">Price $6</p>
                            <input type="button" value="Add to cart">


                        </div>

                      </div>
                    </div>

                         <!---3rd product----->

                    <div class="prod-box" style="margin-left: 50px">
                      <img src="/static/Plants/finalflower3.jpg" alt="Some of our best plants" >
                      <div class="prod-trans" >
                        <div class="prod-feature">

                            <p>Tulip</p>
                            <p style="color:#fff;font-weight: bold">Price $8</p>
                            <input type="button" value="Add to cart">


                        </div>

                      </div>
                    </div>


                </div>

  {% endblock content %}
</body>

{% include "Butterfly/footer.html" %}

Butterfly/templates/Butterfly_Plants/plants.html
{% load staticfiles %}

{% include "Butterfly/header.html" %}


        <!----=====product area====----->
        <div id="heading-block">
                <h2 style="margin-left: 50px; margin-top: 40px;">Indoor Plants</h2>
                </div>

<div class="card">
  <img src="/static/Plants/indoorfinal1.jpg" alt="indoorfinal1" style="width:100%">
  <h1>Areca Palm</h1>
  <p class="price">$2.8</p>
  <p>This leafy plant can be grown anywhere in the house in indirect sunlight.</p>
  <p><button>Add to Cart</button></a></p>
</div>

<div class="card">
  <img src="/static/Plants/indoorfinal2.jpg" alt="indoorfinal2" style="width:100%">
  <h1>English Ivy</h1>
  <p class="price">$3</p>
  <p>This green plant helps in reducing airborne fecal-matter particles. it's very beautiful.</p>
  <p><button>Add to Cart</button></p>
</div>

<div class="card">
  <img src="/static/Plants/indoorfinal3.jpg" alt="Indoor Plants" style="width:100%">
  <h1>Boston Fern</h1>
  <p class="price">$2.89</p>
  <p>Boston ferns can grow quite large and make a showy but elegant addition to your home</p>
  <p><button>Add to Cart</button></p>
</div>

<div class="card">
  <img src="/static/Plants/indoorfinal4.jpg" alt="Indoor Plants" style="width:100%">
  <h1>Slipper Orchid</h1>
  <p class="price">$1.98</p>
  <p>This plant will definitely bring that missing aesthetic vibe to any dull corner of your house.</p>
  <p><button>Add to Cart</button></p>
</div>

<div class="card">
  <img src="/static/Plants/indoorfinal5.jpg" alt="Indoor Plants" style="width:100%">
  <h1>Spider Plant</h1>
  <p class="price">$3.45</p>
  <p>This lovely plant combats benzene, formaldehyde, carbon monoxide and xylene,</p>
  <p><button>Add to Cart</button></p>
</div>

<div class="card">
  <img src="/static/Plants/indoorfinal6.jpg" alt="Indoor Plants" style="width:100%">
  <h1>Snake Plant</h1>
  <p class="price">$3.5</p>
  <p>snake plant is hardy and adds a unique look to your decor with its upright, strap-like leaves.</p>
  <p><button>Add to Cart</button></p>
</div>

<div class="card">
  <img src="/static/Plants/indoorfinal7.jpg" alt="Indoor Plants" style="width:100%">
  <h1>Weeping Fig</h1>
  <p class="price">$4.5</p>
  <p>This leafy plant helps against emissions from curtains, carpets and furniture.</p>
  <p><button>Add to Cart</button></p>
</div>

<div class="card">
  <img src="/static/Plants/indoorfinal8.jpg" alt="Indoor Plants" style="width:100%">
  <h1>Peace Lily</h1>
  <p class="price">$3.2</p>
  <p>The peace lily offers elegance and beauty with a unique look. It prefers bright</p>
  <p><button>Add to Cart</button></p>
</div>


{% include 'Butterfly/footer.html' %}

Butterfly/templates/Seed/seeds.html
{% load staticfiles  %}

{% include "Butterfly/header.html" %}


<h1 id="seed1"> Flower seeds</h1>
<div class="card">
   <img src="apple.jpg" alt="Flower" style="width: 210px; height: 260px; margin-left: 10px;margin-top: 10px;margin-right: 10px;">
 <h1 style="
    margin-top: 0px;
    margin-bottom: 0px;
">Apple<br/>Seeds</h1>
<p class="price" style="
    margin-top: 5px;
    margin-bottom: 5px;
">$...</p>
<p> An apple is a sweet, edible fruit produced by an apple tree (Malus pumila).</p>

  <p><button>Add to Cart</button></p>
</div>
<div class="card">
   <img src="guava.jpg" alt="Flower" style="width: 210px; height: 260px; margin-left: 10px;margin-top: 10px;margin-right: 10px;">
 <h1 style="
    margin-top: 0px;
    margin-bottom: 0px;
">Guava<br/>Seeds</h1>
<p class="price" style="
    margin-top: 5px;
    margin-bottom: 5px;
">$...</p>
<p> Guava is common fruit cultivated in tropical and subtropical regions.</p>

  <p><button>Add to Cart</button></p>
</div>
<div class="card">
   <img src="kiwi1.jpg" alt="Flower" style="width: 210px; height: 260px; margin-left: 10px;margin-top: 10px;margin-right: 10px;">
 <h1 style="
    margin-top: 0px;
    margin-bottom: 0px;
">Kiwi<br/>Seeds</h1>
<p class="price" style="
    margin-top: 5px;
    margin-bottom: 5px;s
">$...</p>
<p>Kiwifruit or Kiwi is a Chinese gooseberry.<br/><br/></p>

  <p><button>Add to Cart</button></p>
</div>
<div class="card">
   <img src="lichi1.jpg" alt="Flower" style="width: 210px; height: 260px; margin-left: 10px;margin-top: 10px;margin-right: 10px;">
 <h1 style="
    margin-top: 0px;
    margin-bottom: 0px;
">Litchi<br/>Seeds</h1>
<p class="price" style="
    margin-top: 5px;
    margin-bottom: 5px;
">$...</p>
<p> Lychee is the sole member of the genus Litchi in the soapberry family.</p>

  <p><button>Add to Cart</button></p>
</div>

<hr />
<div class="container1">
   <img src="seed/" alt="seeds" id="image1"/>
     <img src="apples.jpg" alt="seeds" id="one"/>
     <img src="guava.jpg" alt="seeds" id="two"/>
     <img src="watermelom.jpg" alt="seeds" id="three"/>

<div class="card2">
   <img src="mango1.jpg" alt="Flower" style="width: 210px; height: 260px; margin-left: 10px;margin-top: 10px;margin-right: 10px;">
 <h1 style="
    margin-top: 0px;
    margin-bottom: 0px;
">Mango<br/>Seeds</h1>
<p class="price" style="
    margin-top: 5px;
    margin-bottom: 5px;
">$...</p>
<p> Mangoes are juicy stone fruit from numerous species of tropical trees.</p>


  <p><button>Add to Cart</button></p>
</div>
<div class="card2">
   <img src="melon1.jpg" alt="Flower" style="width: 210px; height: 260px; margin-left: 10px;margin-top: 10px;margin-right: 10px;">
 <h1 style="
    margin-top: 0px;
    margin-bottom: 0px;
">Melon<br/>Seeds</h1>
<p class="price" style="
    margin-top: 5px;
    margin-bottom: 5px;
">$...</p>
<p> A melon are plants of the family Cucurbitaceae with sweet edible, fleshy fruit.</p>

  <p><button>Add to Cart</button></p>
</div>
<div class="card2">
   <img src="orange1.jpg" alt="Flower" style="width: 210px; height: 260px; margin-left: 10px;margin-top: 10px;margin-right: 10px;">
 <h1 style="
    margin-top: 0px;
    margin-bottom: 0px;
">Orange<br/>Seeds</h1>
<p class="price" style="
    margin-top: 5px;
    margin-bottom: 5px;
">$...</p>
<p> The orange is the fruit of the citrus species in the family Rutaceae</p>

  <p><button>Add to Cart</button></p>
</div>
<div class="card2">
   <img src="papaya1.jpg" alt="Flower" style="width: 210px; height: 260px; margin-left: 10px;margin-top: 10px;margin-right: 10px;">
 <h1 style="
    margin-top: 0px;
    margin-bottom: 0px;
">Papaya<br/>Seeds</h1>
<p class="price" style="
    margin-top: 5px;
    margin-bottom: 5px;
">$...</p>
<p> The papaya is a small, sparsely branched tree, usually with a single stem.</p>

  <p><button>Add to Cart</button></p>
</div>

<h1 id="veg" >Vegetable Seeds </h1>
<div class="card3">
   <img src="brinjal.jpg" alt="Flower" style="width: 210px; height: 260px; margin-left: 10px;margin-top: 10px;margin-right: 10px;">
 <h1 style="
    margin-top: 0px;
    margin-bottom: 0px;
">Brinjal<br/>Seeds</h1>
<p class="price" style="
    margin-top: 5px;
    margin-bottom: 5px;
">$...</p>
<p> Brinjal are used extensively in all parts of the world because of the soft, creamy flesh. </p>

  <p><button>Add to Cart</button></p>
</div>
<div class="card3">
   <img src="broccoli.jpg" alt="Flower" style="width: 210px; height: 260px; margin-left: 10px;margin-top: 10px;margin-right: 10px;">
 <h1 style="
    margin-top: 0px;
    margin-bottom: 0px;
">Broccoli<br/>Seeds</h1>
<p class="price" style="
    margin-top: 5px;
    margin-bottom: 5px;
">$...</p>
<p> Broccoli is an edible green plant in the cabbage family.<br/> <br/></p>

  <p><button>Add to Cart</button></p>
</div>
<div class="card3">
   <img src="cabbage.jpg" alt="Flower" style="width: 210px; height: 260px; margin-left: 10px;margin-top: 10px;margin-right: 10px;">
 <h1 style="
    margin-top: 0px;
    margin-bottom: 0px;
">Cabbage<br/>Seeds</h1>
<p class="price" style="
    margin-top: 5px;
    margin-bottom: 5px;
">$...</p>
<p> Cabbage is a leafy green biennial plant grown as an annual vegetable crop.</p>

  <p><button>Add to Cart</button></p>
</div>
<div class="card3">
   <img src="carrot.jpg" alt="Flower" style="width: 210px; height: 260px; margin-left: 10px;margin-top: 10px;margin-right: 10px;">
 <h1 style="
    margin-top: 0px;
    margin-bottom: 0px;
">Carrot<br/>Seeds</h1>
<p class="price" style="
    margin-top: 5px;
    margin-bottom: 5px;
">$...</p>
<p> The carrot is a root vegetable, usually orange, red, white, and yellow in color.<br/></p>

  <p><button>Add to Cart</button></p>
</div>
<div class="card4">
   <img src="onion.jpg" alt="Flower" style="width: 210px; height: 260px; margin-left: 10px;margin-top: 10px;margin-right: 10px;">
 <h1 style="
    margin-top: 0px;
    margin-bottom: 0px;
">Onion<br/>Seeds</h1>
<p class="price" style="
    margin-top: 5px;
    margin-bottom: 5px;
">$...</p>
<p> The onion is a vegetable that is the most widely cultivated species of the genus Allium.</p>

  <p><button>Add to Cart</button></p>
</div>
<div class="card4">
   <img src="potato.jpg" alt="Flower" style="width: 210px; height: 260px; margin-left: 10px;margin-top: 10px;margin-right: 10px;">
 <h1 style="
    margin-top: 0px;
    margin-bottom: 0px;
">Potato<br/>Seeds</h1>
<p class="price" style="
    margin-top: 5px;
    margin-bottom: 5px;
">$...</p>
<p>The potato is a starchy, tuberous crop from the Solanum tuberosum.</p>

  <p><button>Add to Cart</button></p>
</div>
<div class="card4">
   <img src="reddish.jpg" alt="Flower" style="width: 210px; height: 260px; margin-left: 10px;margin-top: 10px;margin-right: 10px;">
 <h1 style="
    margin-top: 0px;
    margin-bottom: 0px;
">Raddish<br/>Seeds</h1>
<p class="price" style="
    margin-top: 5px;
    margin-bottom: 5px;
">$...</p>
<p> Radishes are being mostly eaten raw as a crunchy salad vegetable.</p>

  <p><button>Add to Cart</button></p>
</div>
<div class="card4">
   <img src="spring bean.jpg" alt="Flower" style="width: 210px; height: 260px; margin-left: 10px;margin-top: 10px;margin-right: 10px;">
 <h1 style="
    margin-top: 0px;
    margin-bottom: 0px;
">Spring bean<br/>Seeds</h1>
<p class="price" style="
    margin-top: 5px;
    margin-bottom: 5px;
">$...</p>
<p> A bean is a seed of genera of the flowering plant family Fabaceae.</p>

  <p><button>Add to Cart</button></p>
</div>
</body>

{% include "Butterfly/footer.html" %}

Butterfly/templates/form/form.html
<!DOCTYPE html>
<html>
<link rel="stylesheet" href="form.css">
<body>

<form action="/action_page.php" style="border:1px solid #ccc;width: 565px;height: 600px; margin-top:50px; margin-left:400px;">
  <div class="container">
    <h1>Sign In</h1>
    <p>Please fill in this form to create an account.</p>
    <hr>

    <label for="Name"><b>Name</b></label>
    <input type="text" placeholder="Enter name" name="Name" required="">
	<label for="Username"><b>Username</b></label>
    <input type="text" placeholder="Enter username" name="Usr" required="">
	<label for="email"><b>Email</b></label>
    <input type="text" placeholder="Enter Email" name="email" required="">

    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="psw" required="">

    <label for="psw-repeat"><b>Repeat Password</b></label>
    <input type="password" placeholder="Repeat Password" name="psw-repeat" required="">

    <label>
      <input type="checkbox" checked="checked" name="remember" style="margin-bottom:15px"> Remember me
    </label>

    <p>By creating an account you agree to our <a href="#" style="color:dodgerblue">Terms &amp; Privacy</a>.</p>

    <div class="clearfix">
      <button type="button" class="cancelbtn">Cancel</button>
      <button type="submit" class="signupbtn">Sign Up</button>
    </div>
  </div>
</form>

</body>
</html>